[shape]                                     # shapers configuration
    ignore_ids = []                         # ignore (don't shape) certain IP addresses (VIP)
    rebalance_threshold = 500.0             # bandwidth difference between routers, when do rebalance

    [[shape.devices]]                       # array of the shaping devices
        addr = "shaper-device0:8728"        # device address
        username = ""                       # routerOS username
        password = ""                       # routerOS password
        coef = 0.3                          # weight of the device in balancing calculation

    [[shape.devices]]                       # ...
        addr = "shaper-device1:8728"
        username = ""
        password = ""
        coef = 1.0

[firewall]                                  # firewall device credentials
    addr = "firewall-device:8728"
    username = ""
    password = ""

[acl]                                       # ACL's for subscribers
    list_allow = "Allow"                    # a list with enabled services
    list_deny = "Deny"                      # a list with disabled services

[[pppoe]]                                   # array of PPPoE devices
                                            # (for terminating PPPoE sessions by disabling services)
    addr = "ppp0.mk:8728"                   # device address
    username = ""                           # routerOS username
    password = ""                           # routerOS password

[[pppoe]]                                   # ...
    addr = "ppp1.mk:8728"
    username = ""
    password = ""

[billing]                                   # UTM5 billing settings

    # text of getting subscribers profiles DB query
    get_users_query = """
    select
        concat_ws('#', u.login, a.id, atl.id) as name,
        t.name as tname,
        t.comments as tcomments,
        group_concat(inet_ntoa(ip & 0xFFFFFFFF)) as ips,
        a.int_status as status
    from
        users as u
            join users_accounts as uacc on uacc.uid = u.id
            join accounts as a on a.id = uacc.account_id
            join account_tariff_link as atl on atl.account_id = a.id
            join tariffs as t on t.id = atl.tariff_id
            join service_links as sl on atl.id = sl.tariff_link_id
            join iptraffic_service_links as ipsl on ipsl.id = sl.id
            join ip_groups as ipgr on ipgr.ip_group_id = ipsl.ip_group_id

    where u.is_deleted < 1
      and uacc.is_deleted < 1
      and atl.is_deleted < 1
      and sl.is_deleted < 1
      and ipsl.is_deleted < 1
      and ipgr.is_deleted < 1
    group by u.login, a.id, atl.id, t.id
    order by name;
    """
    bw_multiplier = 1.05                    # bandwidth multiplier for calculating the simple queue capacity

    [billing.db]                            # UTM5 MySQL DB credentials
        host = ""
        username = ""
        password = ""
        dbname_tih = "UTM5"                 # we have two different billing systems by cities
        dbname_kor = "UTM8"

[mq]                                        # RabbitMQ settings
    url   = "amqp://rabbitmq-server:5672/"  # rMQ server
    queue = "mk"                            # queue name
